### ISSUE TITLE
Harold Halibut ultrawide fix crashes to desktop

### ISSUE THREAD

**Issue by selim1965** [RoseTheFlower/UltrawideIndex#73]
I copied the files into the `Contents` folder (Game Pass version) but after the initial logo the game crashes to desktop.

My resolution is set to 3440x1440.

**Comment by selim1965** [comment]
Disabled the option `enabled` to `false` in `doorstop_config.ini`. Ran the game, changed the resolution to a lower setting, exited the game and then re-enabled in doorstop_config and then ran the game again this time it launched. After that changed the resolution to 3440x1440. But after that every time I launch the game it crashes.

**Comment by RoseTheFlower** [comment]
It's hard to tell why that happens. There's at least one user playing the game with my mod without the crashing. You could try enabling all kinds of logging in \BepInEx\config\BepInEx.cfg, then checking the log file.

**Comment by RoseTheFlower** [comment]
I implemented a few additional checks for v1.0.0.1 released just now, but that's probably the most I can do without knowing more.

**Comment by selim1965** [comment]
Thanks! I tried the 1.1 patch and the first time it crashed but after that it consistently seems to work.

**Comment by RoseTheFlower** [comment]
I played through the game with my mod without a single crash, so it looks like the crashes are either unrelated to the mod or potentially related to missing VC dependencies on the affected computers. I'll probably close the issue soon, as it's not something I can look into without being able to reproduce it.

**Comment by Manofield1** [comment]
I got all of the latest VC but it still crashes for me also on 3440x1440 . I am currently reinstalling the game to see if that will help.

**Comment by Manofield1** [comment]
It did not help.

**Comment by Manofield1** [comment]
Though I followed the instructions you mentioned above to check the log file, in the BepInEx.cfg file, I changed some values from 'false' to 'true' in [Logging] and [Logging.Disk], and I set the log levels to 'All'. But somehow, it has stopped crashing. It's really weird. It's really weird.
